# Generated by Django 6.0.1 on 2026-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleinfo',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
    ]
