# Generated by Django 6.0.1 on 2026-01-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cycleinfo_pain_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CycleInfo',
        ),
    ]
